#!/bin/bash

#RUN THIS SCRIPT AS SUDO
#Last updated 21.7.2021 JP

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
USER_HOME=$(getent passwd $SUDO_USER | cut -d: -f6)

#1 APT UPDATE
apt update

#2 APT UPGRADE
apt upgrade

#3 RSYNC
if [ ! -x "$(command -v rsync)" ]; then
	apt install -y rsync
else
	echo "SKIPPING RSYNC: ALREADY INSTALLED..."
fi

#4 LOG2RAM
if [ ! -f /etc/log2ram.conf ]; then
	cd $USER_HOME
	mkdir tmp
	cd tmp
	wget https://github.com/azlux/log2ram/archive/master.tar.gz -O log2ram.tar.gz
	tar xf log2ram.tar.gz
	cd $USER_HOME/tmp/log2ram-master
	./install.sh
else
	echo "SKIPPING LOG2RAM: ALREADY INSTALLED..."
fi

#5 FAIL2BAN
if [ ! -f /etc/fail2ban/jail.local ]; then
	apt install -y fail2ban
	cp $SCRIPT_DIR/jail.local /etc/fail2ban/jail.local
	service fail2ban restart
else
	echo "SKIPPING FAIL2BAN: ALREADY INSTALLED..."
fi

#6 ALIASES
if [ ! -f $USER_HOME/.bash_aliases ]; then
	echo "CREATING ALIASES..."
	cp $SCRIPT_DIR/tmp_aliases $USER_HOME/.bash_aliases
	[[ $SUDO_USER ]] && chown "$SUDO_USER" $USER_HOME/.bash_aliases
else
	echo "ALIASES NOT CREATED!..."
fi

#7 BASHRC
echo "UPDATING BASHRC IF NEEDED..."

if ! grep -q "measure_temp" $USER_HOME/.bashrc; then
	echo "/opt/vc/bin/vcgencmd measure_temp" >> $USER_HOME/.bashrc
	echo "Raspberry CPU temp on login added..."
fi

if ! grep -q "LAST APT" $USER_HOME/.bashrc; then
	echo 'echo "LAST APT UPDATE WAS: $(ls -l /var/cache/apt/pkgcache.bin | cut -d"' '" -f6,7,8)"' >> $USER_HOME/.bashrc
	echo "Last APT update date on login added..."
fi

# FINISHED
cd $USER_HOME
echo "LAST APT UPDATE WAS: $(ls -l /var/cache/apt/pkgcache.bin | cut -d' ' -f6,7,8)"
echo "Script ready. REBOOT NOW!"
exit
